version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Prep yarn global adds
      - run: |
          mkdir ~/.yarn-global
          yarn config set prefix ~/.yarn-global
          export PATH="$PATH:$(yarn global bin)"
          echo $PATH

      # Install globals needed for Github integrations
      - run: |
          yarn global add greenkeeper-lockfile@1.7.2
          yarn global add coveralls@2.13.1

      # Update yarn.lock
      - run: greenkeeper-lockfile-update

      - run: yarn test -- --coverage

      # Commit and push yarn.lock
      - run: greenkeeper-lockfile-upload

      # Send coverage to Coveralls
      - run: cat ./.coverage/lcov.info | coveralls
